version: '3'

networks:
  caddy:
    external: true

services:
  caddy:
    restart: unless-stopped
    image: ghcr.io/schniz/home-automation-cluster-caddy:pr-1
    env_file: ./caddy/environment
    environment:
      ROOT_DOMAIN: "home.hagever.com"
      CADDY_INGRESS_NETWORKS: caddy
    networks:
      - caddy
    volumes:
      - ./caddy-data/:/data/caddy/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - published: 443
        target: 443
      - published: 80
        target: 80
    labels:
      caddy: '*.{env.ROOT_DOMAIN}'
      caddy.tls.dns: cloudflare {env.CF_API_TOKEN}
      caddy.1_@caddy: host caddy.{env.ROOT_DOMAIN}
      caddy.1_handle: '@caddy'
      caddy.1_handle.request_header: Host "localhost:2019"
      caddy.1_handle.reverse_proxy: http://localhost:2019
      caddy.999_@ha: host ha.{env.ROOT_DOMAIN}
      caddy.999_handle: '@ha'
      caddy.999_handle.reverse_proxy: http://192.168.31.167:8123
      caddy.1000_@media: host media.{env.ROOT_DOMAIN}
      caddy.1000_handle: '@media'
      caddy.1000_handle.reverse_proxy: http://192.168.31.89:8096

  transmission:
    restart: unless-stopped
    container_name: transmission
    image: linuxserver/transmission
    networks:
      - caddy
    labels:
      caddy: '*.{env.ROOT_DOMAIN}'
      caddy.2_@torrent: host torrent.{env.ROOT_DOMAIN}
      caddy.2_handle: '@torrent'
      caddy.2_handle.reverse_proxy: '{{upstreams 9091}}'
    environment:
      - PUID="1000"
      - PGID="1000"
      - TZ="Asia/Jerusalem"
    volumes:
      - /media/SchlezExt2/library/downloads:/downloads
      - /media/SchlezExt2/configs/transmission:/config

  cloudflare-ddns:
    restart: unless-stopped
    image: oznu/cloudflare-ddns:latest
    env_file: ./cloudflare-ddns/environment
    environment:
      - ZONE=hagever.com
      - SUBDOMAIN=v
      - PROXIED=false

  jackett:
    networks:
      - caddy
    labels:
      caddy: '*.{env.ROOT_DOMAIN}'
      caddy.3_@jackett: host jackett.{env.ROOT_DOMAIN}
      caddy.3_handle: '@jackett'
      caddy.3_handle.reverse_proxy: '{{upstreams 9117}}'
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Asia/Jerusalem"
    volumes:
      - /media/SchlezExt2/configs/jackett:/config
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - caddy
    labels:
      caddy: '*.{env.ROOT_DOMAIN}'
      caddy.4_@sonarr: host sonarr.{env.ROOT_DOMAIN}
      caddy.4_handle: '@sonarr'
      caddy.4_handle.reverse_proxy: '{{upstreams 8989}}'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Asia/Jerusalem"
    volumes:
      - /media/SchlezExt2/configs/sonarr:/config
      - /media/SchlezExt2/library/tv:/tv
      - /media/SchlezExt2/library/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - caddy
    labels:
      caddy: '*.{env.ROOT_DOMAIN}'
      caddy.5_@radarr: host radarr.{env.ROOT_DOMAIN}
      caddy.5_handle: '@radarr'
      caddy.5_handle.reverse_proxy: '{{upstreams 7878}}'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Asia/Jerusalem"
    volumes:
      - /media/SchlezExt2/configs/radarr:/config
      - /media/SchlezExt2/library/movies:/movies
      - /media/SchlezExt2/library/downloads:/downloads
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Asia/Jerusalem"
    volumes:
      - /media/SchlezExt2/configs/jellyfin:/config
      - /media/SchlezExt2/library/tv:/data/tvshows
      - /media/SchlezExt2/library/movies:/data/movies
      - type: tmpfs
        target: /tmp-transcoding
    restart: unless-stopped
