repositories:
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: node-feature-discovery
    url: https://kubernetes-sigs.github.io/node-feature-discovery/charts

releases:
  - name: kubernetes-dashboard
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 5.0.4

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.6.1
    values:
      - installCRDs: true

  - name: node-feature-discovery
    namespace: node-feature-discovery
    chart: node-feature-discovery/node-feature-discovery
    version: 0.9.0
    values:
      - image:
          repository: "raspbernetes/node-feature-discovery"
          tag: "v0.9.0"

  - name: home
    chart: ./home
    values:
      - ./home_secrets.yaml
    needs:
      - kubernetes-dashboard
      - cert-manager
