---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: playing
data:
  schl.es.db: |
    schl.es.        IN  SOA dns.schl.es. gal.spitfire.co.il. 2015082541 7200 3600 1209600 3600
    *.schl.es.    IN A 192.168.31.246
  Corefile: |
    .:53 {
        forward . 8.8.8.8 9.9.9.9
        log
        errors
        cache
        reload
    }

    schl.es:53 {
        file /myconfigmap/schl.es.db
        log
        errors
        reload
        cache
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: playing
  name: my-dns-server
spec:
  revisionHistoryLimit: 1 # Default to 10 if not specified
  selector:
    matchLabels:
      run: my-dns-server
  replicas: 1
  template:
    metadata:
      labels:
        run: my-dns-server
    spec:
      containers:
      - name: coredns
        image: coredns/coredns
        args: ["-conf", "/myconfigmap/Corefile"]
        volumeMounts:
          - name: myconfigmap
            mountPath: "/myconfigmap"
            readOnly: true
        ports:
        - containerPort: 53
          protocol: UDP
          hostPort: 53
          name: udp-udp
        - containerPort: 53
          hostPort: 53
          protocol: TCP
          name: tcp-dns
      volumes:
        - name: myconfigmap
          configMap:
            name: my-config-map
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   namespace: playing
#   name: my-dns-service
#   labels:
#     app: dns-server
# spec:
#   type: LoadBalancer
#   sessionAffinity: ClientIP
#   ports:
#   - port: 53
#     protocol: UDP
#   - port: 53
#     protocol: TCP
#   selector:
#     run: my-dns-server
