apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ddns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
  labels:
    app: cloudflare-ddns
    hagever.com/version: '1'
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: ddns-agent
          image: oznu/cloudflare-ddns:latest
          env:
            - name: ZONE
              value: {{ .Values.cloudflare.root_domain }}
            - name: SUBDOMAIN
              value: {{ .Values.cloudflare.vpn_subdomain }}
            - name: PROXIED
              value: 'false'
            - name: API_KEY
              value: {{ .Values.cloudflare.api_token }}
