---
# {{- $namespace := "home-assistant" -}}
# {{- $subdomain := .Values.apps.home_assistant.subdomain -}}
# {{- $domain := print $subdomain "." .Values.ingress.base_domain -}}
---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ $namespace }}
  name: home-assistant-config
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "2Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/SchlezExt2/homeassistant-config"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $namespace }}
  name: "home-assistant-config"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app: home-assistant
    hagever.com/version: '1'
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      volumes:
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: home-assistant-config
      containers:
        - name: homeassistant
          securityContext:
            privileged: true
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
              name: http
          volumeMounts:
            - mountPath: "/config"
              name: home-assistant-config
          env:
            - name: TZ
              value: Asia/Jerusalem
            - name: FOLDER
              value: /
          livenessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: {{ $namespace }}
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8123
  clusterIP: None
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  namespace: {{ $namespace }}
  name: homeassistant
subsets:
- addresses:
  - ip: 192.168.31.90
  ports:
  - name: app
    port: 8123
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: {{ $namespace }}
spec:
  tls:
    - hosts:
        - {{ $domain | quote }}
  rules:
  - host: {{ $domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: homeassistant
            port:
              number: 80
        path: /
        pathType: Prefix
