---
# {{- $subdomain := .Values.apps.home_assistant.subdomain -}}
# {{- $domain := print $subdomain "." .Values.ingress.base_domain -}}
---

apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant

---

apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8123
  clusterIP: None
  type: ClusterIP

---

apiVersion: v1
kind: Endpoints
metadata:
  namespace: home-assistant
  name: homeassistant
subsets:
- addresses:
  - ip: 192.168.31.167
  ports:
  - name: app
    port: 8123
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  tls:
    - hosts:
        - {{ $domain | quote }}
  rules:
  - host: {{ $domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: homeassistant
            port:
              number: 80
        path: /
        pathType: Prefix
