---
# {{- $subdomain := .Values.apps.ical_http_sensor.subdomain -}}
# {{- $domain := print $subdomain "." .Values.ingress.base_domain -}}
---

apiVersion: v1
kind: Namespace
metadata:
  name: ical-http-sensor

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ical-http-sensor
  namespace: ical-http-sensor
  labels:
    app: ical-http-sensor
    hagever.com/version: '1'
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: ical-http-sensor
  template:
    metadata:
      labels:
        app: ical-http-sensor
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: server
          image: ghcr.io/schniz/ical_http_server:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: ical-http-sensor
  namespace: ical-http-sensor
  labels:
    app: ical-http-sensor
spec:
  selector:
    app: ical-http-sensor
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ical-http-sensor
  namespace: ical-http-sensor
spec:
  tls:
    - hosts:
        - {{ $domain | quote }}
  rules:
  - host: {{ $domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: ical-http-sensor
            port:
              number: 8080
        path: /
        pathType: Prefix
