on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    environment: home
    steps:
      - uses: actions/checkout@v2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          playbook: ansible/main.yaml
          directory: ./
          requirements: ansible/galaxy-requirements.yml
          # key: ${{ secrets.SSH_SECRET_KEY }}
          inventory: |
            [all]
            localhost
          options: --connection=local

      - name: reveal secrets
        run: |
          git secret reveal -f

      - name: apply docker-compose.yml
        run: |
          docker compose --project-name deployment up -d
