on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: [self-hosted, pi4]
    environment: home
    steps:
      - uses: actions/checkout@v2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        with:
          playbook: ansible/main.yaml
          directory: ./
          requirements: ansible/galaxy-requirements.yml
          # key: ${{ secrets.SSH_SECRET_KEY }}
          inventory: |
            [all]
            localhost
          options:
            --connection=local

      - name: install git secret and gpg
        run: |
          sudo apt-get update
          sudo apt-get install git-secret gnupg -y

      # - name: import gpg private key
      #   run: |
      #     echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --batch --yes --pinentry-mode loopback --import

      - name: reveal secrets
        run: |
          git secret reveal -f

      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_SECRET_KEY }}
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: apply docker-compose.yml
        run: |
          docker-compose --project-name deployment up -d
