on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: home
    steps:
      - uses: actions/checkout@v2
      - name: Connect to Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_TOKEN }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
        with:
          playbook: playbook.yaml
          directory: ./
          key: ${{ secrets.SSH_SECRET_KEY }}
          inventory: |
            [all]
            192.168.31.89  ansible_user=pi

      - name: install git secret and gpg
        run: |
          sudo apt-get update
          sudo apt-get install git-secret gnupg -y

      - name: import gpg private key
        run: |
          echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --batch --yes --pinentry-mode loopback --import

      - name: reveal secrets
        run: |
          git secret reveal -f

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_SECRET_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: apply docker-compose.yml
        run: |
          docker-compose up -d --projec-name deployment
        env:
          DOCKER_HOST: ssh://pi@192.168.31.89
